<?php
/**
 * CodeVault secure multi-product checkout.
 * Copyright (c) 2026 Alen Pepa. All rights reserved.
 */
declare(strict_types=1);
require 'payments.php';

$requestedId=(int)($_GET['id']??0);$ids=$requestedId>0?[$requestedId]:cart_ids();
if($_SERVER['REQUEST_METHOD']==='POST'&&!empty($_SESSION['checkout_ids'])&&is_array($_SESSION['checkout_ids']))$ids=array_map('intval',$_SESSION['checkout_ids']);
$products=products_by_ids($ids);if(!$products)redirect('cart.php');
$_SESSION['checkout_ids']=array_map(fn(array $product):int=>(int)$product['id'],$products);$total=array_reduce($products,fn(float $sum,array $product):float=>$sum+(float)$product['price'],0.0);
$methods=[];if(enabled('paypal_enabled'))$methods['paypal']=['PayPal',t('payment.paypal'),'PP'];if(enabled('btcpay_enabled'))$methods['btcpay']=['Bitcoin',t('payment.btc'),'₿'];if(enabled('manual_enabled',true))$methods['manual']=[setting('manual_title',t('payment.manual')),t('payment.manual'),'↗'];
$error='';$manualReference='';$orderPublicId='';$accessToken='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$name=safe_text($_POST['name']??'',100);$email=filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL);$method=is_string($_POST['payment_method']??null)?$_POST['payment_method']:'';$human=captcha_verify($_POST['captcha']??'');$honeypot=trim((string)($_POST['website']??''));$identifier=client_hash();
    if(rate_limited('checkout',$identifier,12,900))$error=t('error.rate');elseif(!$human||$honeypot!=='')$error=t('error.captcha');elseif(!$name||!$email)$error=t('error.required');elseif(!isset($methods[$method]))$error=t('error.payment_method');else{
        $orderPublicId=strtoupper(bin2hex(random_bytes(8)));$accessToken=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$manualReference=safe_text($_POST['manual_reference']??'',160);$orderId=0;
        $db->beginTransaction();try{$stmt=$db->prepare('INSERT INTO orders(public_id,access_token_hash,customer_name,customer_email,product_id,amount,status,payment_method,payment_reference,ip_hash) VALUES(?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$orderPublicId,order_access_hash($accessToken),$name,strtolower((string)$email),$products[0]['id'],$total,$method==='manual'?'pending':'paying',$method,$manualReference,client_hash()]);$orderId=(int)$db->lastInsertId();$item=$db->prepare('INSERT INTO order_items(order_id,product_id,title_snapshot,price_snapshot) VALUES(?,?,?,?)');foreach($products as $product)$item->execute([$orderId,$product['id'],product_copy($product,'title'),$product['price']]);$db->commit();remember_order_access($orderPublicId,$accessToken);
            $order=['id'=>$orderId,'public_id'=>$orderPublicId,'amount'=>$total,'access_token'=>$accessToken];$paymentProduct=$products[0];$paymentProduct['_payment_title']=count($products)>1?'CodeVault bundle ('.count($products).' products)':product_copy($products[0],'title');
            if($method==='paypal'){$payment=paypal_create($order,$paymentProduct);$db->prepare('UPDATE orders SET payment_reference=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$payment['id'],$orderId]);event_record('checkout',$identifier,true,['method'=>'paypal','items'=>count($products)]);cart_clear();provider_redirect($payment['url'],'paypal');}
            if($method==='btcpay'){$payment=btcpay_create($order,$paymentProduct);$db->prepare('UPDATE orders SET payment_reference=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$payment['id'],$orderId]);event_record('checkout',$identifier,true,['method'=>'btcpay','items'=>count($products)]);cart_clear();provider_redirect($payment['url'],'btcpay');}
            event_record('checkout',$identifier,true,['method'=>'manual','items'=>count($products)]);cart_clear();redirect('order.php?order='.rawurlencode($orderPublicId).'&access='.rawurlencode($accessToken));
        }catch(Throwable $exception){if($db->inTransaction())$db->rollBack();if($orderId>0)$db->prepare('UPDATE orders SET status="payment_error",updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$orderId]);error_log('Checkout provider error: '.$exception->getMessage());event_record('checkout',$identifier,false,['method'=>$method]);$error=t('error.payment');}
    }
    if($error!=='')event_record('checkout',$identifier??client_hash(),false,['reason'=>'validation']);
}
$captchaQuestion=captcha_new();$pageTitle=t('checkout.label');require 'partials/header.php';
?>
<section class="checkout-shell"><div class="checkout-main"><a class="back" href="cart.php">← <?= e(t('checkout.back')) ?></a><span class="kicker"><?= e(t('checkout.label')) ?></span><h1><?= e(t('checkout.title')) ?></h1><?php if(isset($_GET['cancelled'])):?><p class="notice"><?= e(t('checkout.cancelled')) ?></p><?php endif;?><p class="checkout-count"><?= count($products) ?> <?= e(t('checkout.items')) ?></p>
<form method="post" id="checkout-form" autocomplete="off"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><label class="hp" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><div class="row"><label><?= e(t('form.name')) ?><input name="name" maxlength="100" required value="<?= e(safe_text($_POST['name']??'',100)) ?>"></label><label><?= e(t('form.email')) ?><input type="email" name="email" maxlength="190" required value="<?= e(safe_text($_POST['email']??'',190)) ?>"></label></div><div class="method-title"><?= e(t('payment.method')) ?></div><div class="payment-methods"><?php foreach($methods as $key=>$method):?><label class="payment-card"><input type="radio" name="payment_method" value="<?= e($key) ?>" <?= $key===array_key_first($methods)?'checked':'' ?>><span class="pay-icon"><?= e($method[2]) ?></span><span><b><?= e($method[0]) ?></b><small><?= e($method[1]) ?></small></span><i>✓</i></label><?php endforeach;?></div><?php if(!$methods):?><p class="error"><?= e(t('error.no_methods')) ?></p><?php endif;?><label class="manual-ref" hidden><?= e(t('payment.reference')) ?><input name="manual_reference" maxlength="160"></label><label><?= e(t('form.captcha')) ?> · <b><?= e($captchaQuestion) ?></b><input name="captcha" inputmode="numeric" maxlength="4" required placeholder="<?= e(t('form.answer')) ?>"></label><?php if($error):?><p class="error" role="alert"><?= e($error) ?></p><?php endif;?><button class="button wide" type="submit" <?= !$methods?'disabled':'' ?>><?= e(t('payment.continue')) ?><span>→</span></button><div class="security-note">⌁ <?= e(t('payment.secure')) ?></div></form></div>
<aside class="order-summary"><div class="summary-art">&lt;CV /&gt;</div><span><?= e(t('order.summary')) ?></span><?php foreach($products as $product):?><div class="summary-product"><h3><?= e(product_copy($product,'title')) ?></h3><p><?= e($product['tech']) ?></p><b><?= money((float)$product['price']) ?></b></div><?php endforeach;?><div class="summary-line"><span><?= e(t('order.license')) ?></span><b><?= e(t('order.included')) ?></b></div><div class="summary-total"><span><?= e(t('order.total')) ?></span><b><?= money($total) ?></b></div></aside></section>
<?php require 'partials/footer.php'; ?>
